services:
    kernel.listener.exception_listener:
        class: Bt\Bundle\CustomMessageExceptionBundle\Listener\ExceptionListener
        arguments: ['@templating', '@kernel']
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}
